name: Create a new GitHub Release

on:
  # push:
  #   tags:
  #     - "*"
  workflow_dispatch:
    inputs:
      tag:
        description: 'The type of version bump'
        required: true
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: requirements/dev.txt

      - name: Install pandoc
        run: sudo apt install -y pandoc

      - name: Install requirements
        run: pip install scriv bump-my-version

      - name: Bump version
        run: bump-my-version bump ${{ github.event.inputs.tag }}

      # - name: Bump version and push tag
      #   id: tag_version
      #   uses: mathieudutour/github-tag-action@v6.2
      #   with:
      #     github_token: ${{ github.token }}
      #     default_bump: ${{ github.event.inputs.tag }}

      - name: Collect changelog
        run: make changelog

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.ref }}
          commit_message: "chore: bump version"

      - name: Create or update GitHub release
        run:
          scriv github-release --repo=bryanttv/openedx-filters
        env:
          GITHUB_TOKEN: ${{ github.token }}
