name: Create a new GitHub Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install requirements
        run: pip install scriv bump-my-version

      - name: Install pandoc for scriv
        run: sudo apt install -y pandoc

      - name: Get current version
        id: version
        run: |
          echo "CURRENT_VERSION=$(bump-my-version show current_version)" >> $GITHUB_OUTPUT

      - name: Create new tag
        id: tag
        run: |
          git tag -a "v${{ steps.version.outputs.CURRENT_VERSION }}" -m "Release v${{ steps.version.outputs.CURRENT_VERSION }}"
          git push origin "v${{ steps.version.outputs.CURRENT_VERSION }}"

      - name: Create GitHub release
        run: scriv github-release --repo=bryanttv/openedx-filters
        env:
          GITHUB_TOKEN: ${{ github.token }}
